# -*- coding: utf-8 -*-
"""NEMA17_HeatSink_ThermalCalculations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nCKIsPxljHpZOatOAX_y0D6m2AFGmAi
"""

import math

voltage = 12            #V
current = 1.5           # A
efficiency = 0.8        # 80% efficient
ambient_temp = 25       # °C
T_max_motor = 60        # °C safe operating temp

fan_voltage = 12        # V
fan_current = 0.05      # A

rho_air = 1.1845        # kg/m^3
k_air = 0.025969        # W/m·K
nu_air = 1.5571e-5      # m^2/s
Pr = 0.71465            # Prandtl number

N = 34 # Number of fins
fin_thickness = 0.0015   # m
air_gap = 0.001          # m
fin_pitch = fin_thickness + air_gap

base_thickness = 0.004          # m (4 mm)
inner_radius = 0.0186           # m (ID)
outer_radius = 0.040            # m (OD)
fin_radial_length = 0.009206    # m
fin_height = 0.0166             # m


V = 5.63 # m/s (estimate)

power = voltage * current
print("Power:", power)

Q_loss = power * (1 - efficiency) # heat generated
print("Power Dissipation (Q) :",  round(Q_loss, 1))

Dh = 2 * ((air_gap * fin_radial_length) / (air_gap + fin_thickness))
Re = (V * Dh) / nu_air
print("Reynolds Number :", Re)

Nu = 0.023 * (Re**(4/5)) * (Pr**(1/3))
h = (Nu * k_air) / Dh
print(f"Nusselt Number: {round(Nu, 2)}")
print(f"Heat Transfer Coefficient (h): {round(h, 2)} W/m²·K")

delta_T = T_max_motor - ambient_temp
A_required = Q_loss / (h * delta_T)
print(f"Required Surface Area: {round(A_required, 6)} m²")

A_actual = 2 * N * fin_thickness * fin_height
print(f"Actual Fin Surface Area: {round(A_actual, 6)} m²")

T_actual = ambient_temp + (Q_loss / (h * A_actual))
print(f"Expected Motor Temperature: {round(T_actual, 2)} °C") #estimate actual motor temp with current design

fan_power = fan_voltage * fan_current
print(f"Fan Power Consumption: {round(fan_power, 2)} W") #fan power estimate

